### ISSUE TITLE
Sleep tracker and mood tracker running on local storage

### ISSUE THREAD

**Issue by Riddhi050803** [Bluesparx/raga#17]
Issue: Replace Local Storage with Database Fetching for Sleep and Mood Tracker
**Current Functionality**
The sleep tracker and mood tracker currently store and retrieve data using localStorage. 
**Expected Functionality**
The app should fetch and store data in a database instead of local storage. 

Note: Please go through the APIs and pages code carefully.

**Comment by devXpraAddy** [comment]
hey i would like to work on this can you assign me this issue

**Comment by Riddhi050803** [comment]
@devXpraAddy Sure, Go for it.
