### ISSUE TITLE
Making navbar responsive 

### ISSUE THREAD

**Issue by mahenoorsalat** [Bluesparx/raga#19]
## PR - Responsiveness of Navbar

1. **Mobile-First Design**: The navbar will be designed using a mobile-first approach, ensuring optimal performance and display on smaller screens before scaling up to larger devices.

2. **Hamburger Menu Implementation**: A hamburger menu will be added for devices with smaller screens to allow easy access to navigation items while conserving space.

3. **Fluid Layout & Font Scaling**: The navbar will be built using a fluid layout (e.g., Flexbox or CSS Grid), with font sizes and padding that adapt responsively based on screen size for enhanced readability and usability.

**Please Assign me this issue .. I will work on it**

@Bluesparx  Thank you :)

**Comment by Bluesparx** [comment]
Hi, someone is already working on it but I'll let you know if needed. Also, please go through open issues before posting a new one :)

**Comment by Riddhi050803** [comment]
This issue has been resolved.
