### ISSUE TITLE
[FRONTEND]: Add blurry background on the navbar

### ISSUE THREAD

**Issue by rajmanna-dev** [Bluesparx/raga#2]
Right now the backgound of the navbar is fully transparent. To improve the visuals its a good idea to add blarry effect to backgound of the navber.

### Screenshots
![Screenshot 2024-10-08 193743](https://github.com/user-attachments/assets/8e655034-517a-448d-8e11-c465a2dc3507)

### Additional context
I would love to contribute on this repo under the `hacktoberfest` labeling.

**Comment by devXpraAddy** [comment]
hey i would like to work on this issue can you assign me this.

**Comment by mrkeshav-05** [comment]
@rajmanna-dev I would like to solve this issue.
Please assign this to me.

**Comment by rajmanna-dev** [comment]
Wall @devXpraAddy @mrkeshav-05 I am a contributor too. I don't have the repo access.

**Comment by Riddhi050803** [comment]
@rajmanna-dev @mrkeshav-05  @devXpraAddy   We are focusing mainly on the backend right now. You can contribute on other potential issues. Thank you.
