### ISSUE TITLE
Add a get started button at home page redirecting to login/signup page

### ISSUE THREAD

**Issue by palak1008jain** [Bluesparx/raga#3]
if someone is new to this ..they don't know that they can keep track only on signup/login
get started button will help them to navigate through it easily

**Comment by Srijan25** [comment]
can you add this issue in hackoberfest

**Comment by palak1008jain** [comment]
yes I would love to contribute this under hacktoberfest labelling

**Comment by Bluesparx** [comment]
Okay!

**Comment by PRAteek-singHWY** [comment]
@Bluesparx i have made the changes and added Get Started button to it 
please check and review it , since this issue wasn't resolved since last 5 hrs so i resolved it
