### ISSUE TITLE
Not working of sign up section

### ISSUE THREAD

**Issue by mayank-0789** [Bluesparx/raga#32]
# Issue: Sign-Up Section Not Functioning

## Summary
The sign-up section of the application is currently not functioning as expected. Users are unable to create new accounts, which could lead to loss of potential users and hinder the growth of our platform.

## Current Behavior
- Users attempting to sign up are met with unresponsive behavior.
- Common issues include:
  - The "Sign Up" button being unresponsive.

## Steps to Reproduce
1. Navigate to the sign-up page.
2. Fill in the required fields (e.g., name, email, password).
3. Click the "Sign Up" button.
4. Observe the behavior ( lack of response).

## Expected Behavior
- Users should be able to enter their information and successfully create an account.
- Upon submission, a confirmation message should be displayed, and users should be redirected to the login page or dashboard.

## Conclusion
Resolving the sign-up section's functionality is critical for maintaining user engagement and ensuring a smooth onboarding experience. This issue should be prioritized for immediate attention.

**Comment by mayank-0789** [comment]
@Bluesparx  please assign this issue to me

**Comment by Bluesparx** [comment]
It's working? Can u elaborate what issue you are facing and how you will solve it.
