### ISSUE TITLE
Fix Fetch User Sleep API 

### ISSUE THREAD

**Issue by Bluesparx** [Bluesparx/raga#36]
**Description:** The Fetch User Sleep API is currently not functioning as expected and is returning errors when attempting to retrieve user sleep data. 

![Screenshot 2024-10-10 114527](https://github.com/user-attachments/assets/cfd55513-01f7-491b-97bf-422a1f45a77c)

Similar bug was fixed for Fetch User Mood as well for reference.

**Comment by abdurrahmaan11265** [comment]
can i work on this

**Comment by Bluesparx** [comment]
Yes
