### ISSUE TITLE
Bug: Show alert on logging in with wrong or non-existent account credentials.

### ISSUE THREAD

**Issue by swarupn17** [Bluesparx/raga#37]
It looks like login validation is correctly happening on the backend, but the error messages aren't being passed or displayed on the frontend. This could be due to a missing or broken error-handling mechanism in the frontend code. We need to ensure that the backend returns meaningful error responses (e.g., `400` for invalid credentials), and the frontend captures and displays these messages to the user (e.g., "Invalid username or password").
<img width="1470" alt="Screenshot 2024-10-10 at 11 59 10 AM" src="https://github.com/user-attachments/assets/97a31710-6144-48ee-abf0-62bcd1f33355">

Please assign this issue to me i can solve it.
Thanks!

**Comment by AbishaKugathasan** [comment]
Could I please work on this issue?

**Comment by AbishaKugathasan** [comment]
@Bluesparx I have made a PR for this bug: https://github.com/Bluesparx/raga/pull/90
Please let me know if there is anything else I should add.
