### ISSUE TITLE
Improve the Frontend of the Sign-Up Page

### ISSUE THREAD

**Issue by DeviSriSaiCharan** [Bluesparx/raga#4]
## Description: 
The current Sign-Up page looks quite plain and lacks design elements that can enhance the user experience. Specifically, there is no margin at the bottom of the form, which impacts the overall spacing and aesthetics. I'd like to improve the frontend design to make it more visually appealing and user-friendly.

## Proposed Solution:
- Add proper margins and padding to improve the form layout.
- Enhance the overall design with better color schemes, fonts, and alignment.
- Implement responsive design to ensure the page looks good on all devices.
- Add animations or hover effects to make the form more interactive.

## Additional Context: 
Here’s a screenshot of the current Sign-Up page, showing the lack of margin at the bottom of the form:

![image](https://github.com/user-attachments/assets/9b58a239-3197-4f4c-9670-6e4130323a21)

**Comment by Bluesparx** [comment]
Could you make it responsive as well?

**Comment by DeviSriSaiCharan** [comment]
Yha, i can make it responsive as well.

**Comment by DeviSriSaiCharan** [comment]
Hello @Bluesparx ,

I enhanced the ui of a signup page by adding images and small changes to input fields when they are focued and made the form responsive.

Once checkout the video, if it is good i will send PR to merge it.

https://www.loom.com/share/44fa57b0ce764e548a49079d3c6f3813?sid=24d1a888-2b7f-43ac-abef-c097171dcf9e

**Comment by Bluesparx** [comment]
Seems good! Could you do the same for the login page since they're both inherently same forms. 
ALso, make sure you pull the main branch before opening a pr!

**Comment by DeviSriSaiCharan** [comment]
Hello @Bluesparx,

After pulled the latest repo, i got an error in console 
![image](https://github.com/user-attachments/assets/529683af-bcb6-41d9-bb47-79f91078cc48)

i think this is due to missing of .env file in the frontend..!

**Comment by Bluesparx** [comment]
Great! 
Yes we added firebase auth thanks for noticing, I'll add it in the readme file with instructions :)
