### ISSUE TITLE
Bug: Incorrect Text Color for No Data Message

### ISSUE THREAD

**Issue by abdurrahmaan11265** [Bluesparx/raga#46]
The message "No sleep data available for the selected date. Please log some sleep entries." is currently being displayed in black text, making it difficult to read against the dark background. The text should be in white color to improve visibility.

Expected Behavior: The text should be styled with a white font color to ensure it contrasts well with the background.

Steps to Recreate:
- Go to the website Zen Zone.
- Navigate to the Analytics tab in the navigation bar.
- Select Sleep Graph from the options.
- Choose any date for which no sleep data is available.
- Observe the message "No sleep data available for the selected date. Please log some sleep entries." being displayed in black color, which is hard to read against the dark background.
- Screenshot: Please refer to the attached screenshot for reference.
![Screenshot (361)](https://github.com/user-attachments/assets/12cf9e51-1827-4b3d-a4f7-c68003d593a7)

Request: Kindly assign this issue to me (Mohammed Abdur Rahman) so I can resolve it.

**Comment by abdurrahmaan11265** [comment]
Hi,

I have successfully resolved this issue. Could you kindly label it with "hacktoberfest" and "hacktoberfest-accepted" to reflect the contribution? Your support is greatly appreciated!

Thank you!

**Comment by HarshKumar1121** [comment]
assign this to me i can  resolve within hours with perfection .
