### ISSUE TITLE
Feature Request: Add Hover Labels for Buttons on the Breathing Exercise Page

### ISSUE THREAD

**Issue by abdurrahmaan11265** [Bluesparx/raga#58]
On the breathing exercise page, there are several control buttons (Play, Reset, Brightness, Mute/Unmute, and Play/Pause music) that currently do not display labels when hovered over. Adding hover labels would improve the user experience by clearly indicating the functionality of each button without needing users to guess or rely on memory.

Suggested Labels:

- Yellow Brightness Button: "Dark mode/ Light mode"
- Green Mute/Unmute Button: "Mute/ Unmute"
- Purple Music Button: "Play Music/ Pause Music"

Screenshot for Reference:
![image](https://github.com/user-attachments/assets/1295cc31-8fed-418e-8348-bcc795fb9938)

Request: Kindly assign this issue to me (Mohammed Abdur Rahman) so I can resolve it.

**Comment by Bluesparx** [comment]
Hi, could you also incorporate the background, similar to other pages?

**Comment by abdurrahmaan11265** [comment]
Sure, i can

**Comment by abdurrahmaan11265** [comment]
is this okay?
light mode:
![image](https://github.com/user-attachments/assets/9575ac42-9ae7-45a0-b0d2-54c528a4d461)

dark mode:
![image](https://github.com/user-attachments/assets/ba1eb08b-6b6a-4912-94c7-ed113f4a82c8)

**Comment by Bluesparx** [comment]
Cool!

**Comment by abdurrahmaan11265** [comment]
@Bluesparx I've enhanced the breathing exercise page with hover labels and a consistent background. Could you please review the changes and merge the PR if everything looks good? Also, kindly add the "hacktoberfest-accepted" label if the changes meet the requirements. Thanks!
