### ISSUE TITLE
[Frontend] Like button on post not working (Community)

### ISSUE THREAD

**Issue by Horsmanayo** [Bluesparx/raga#6]

**Comment by Horsmanayo** [comment]
Hi @Bluesparx, can you add the hackoberfest tag to this ticket 

And also, there is an issue with the like post end point, I will create an issue for to this effect

**Comment by Bluesparx** [comment]
@Horsmanayo any updates?

**Comment by Riddhi050803** [comment]
@Horsmanayo, we are assigning this issue to someone else due to the lack of updates. Thank you.
