### ISSUE TITLE
About Us Page is Not Responsive 

### ISSUE THREAD

**Issue by ayushsingh199** [Bluesparx/raga#71]
<img width="402" alt="Screenshot 2024-10-14 at 6 43 50 PM" src="https://github.com/user-attachments/assets/d46b63f7-8437-4c66-858c-f787bb6cbf19">

The about us page is not responsive on mobile devices. We have to make it responsive on mobile devices.

**Comment by ayushsingh199** [comment]
Please assign me this issue , i am willing to work on this.

**Comment by Vardhan-Harsh07** [comment]
@Riddhi050803 @Sahib-Aujla assign to me it can be done very easily by me

**Comment by Bluesparx** [comment]
Hi, sry for the delay we have exams this week..

**Comment by Vardhan-Harsh07** [comment]
@Bluesparx well u can assign it to me u prepare for the exams

**Comment by ayushsingh199** [comment]
i m on it @Vardhan-Harsh07  I'LL do the job you can find another query buddy..

**Comment by Riddhi050803** [comment]
Hi @ayushsingh199 I hope you are on it. Please make the contact page responsive as well (only margin is required).

**Comment by ayushsingh199** [comment]
yes @Riddhi050803 i m on it just need 3-4 days time that's it , i'll do the needful madame'.
