### ISSUE TITLE
Make the Site Mobile Responsive

### ISSUE THREAD

**Issue by tanish0912** [Bluesparx/raga#8]
<img width="332" alt="Screenshot 2024-10-09 at 12 08 00 AM" src="https://github.com/user-attachments/assets/3a796155-07a6-46db-8607-aa6f3d167017">
I am planning to add hamburger menu 
on mobile  which will give website clean look on mobile.

**Comment by tanish0912** [comment]
Please assign me this issue

**Comment by Bluesparx** [comment]
Okay pls work on it
