### ISSUE TITLE
Feature: Fetch sleep logs to the Calendar

### ISSUE THREAD

**Issue by Bluesparx** [Bluesparx/raga#86]
Currently, the calendar only displays the mood log associated to a day. 

Requested Changes:
- Fetch sleep values using the API endpoint from `apiRequest.js`. Display them in the calendar view and modal associated on clicking a day.
- Make these pages responsive on all frame sizes.

Make sure to add screenshots and link this issue in the pull request.

**Comment by nate10j** [comment]
Hi, can I take this issue?
