### ISSUE TITLE
Improve Text formatting in About section on mobile screen

### ISSUE THREAD

**Issue by jayantghadge** [Bluesparx/raga#87]
<img src="https://github.com/user-attachments/assets/14bf4c15-36a3-4eba-87be-a6ba4b5547e3" alt="Description" width="300"/>

### Description
- Text in About section appears cramped on mobile.
- Lines often contain only 1-2 words, affecting readability.
- Screenshot attached for reference.

### Suggestion
- Adjust text width, font size, padding and margin for mobile view.

**Comment by Bluesparx** [comment]
Hi, @jayantghadge someone is already working on this issue. Please do go through open issues before opening new ones.
happy coding :)

**Comment by jayantghadge** [comment]
> Hi, @jayantghadge someone is already working on this issue. Please do go through open issues before opening new ones.
> happy coding :)

Noted, thanks for the update!
