### ISSUE TITLE
Backend of forgot password

### ISSUE THREAD

**Issue by shobhit15082003** [Bluesparx/raga#9]
I can make the entire backend for forgot password where the password will be shared via nodemailer and otp will be generated via otplib.
Techstack will be express.js.

@Bluesparx plz assign me this issue.

**Comment by Riddhi050803** [comment]
@shobhit15082003 Go for it.

**Comment by shobhit15082003** [comment]
hey @Bluesparx there was some problem in my laptop so I was getting it repaired I got it back today(10th october) itself, I will try to make a pr asap.
